name: mfexport
channels:
- conda-forge
- defaults
dependencies:
- python
- pyyaml
- numpy
- pandas
- gdal
- fiona
- rasterio
- shapely
- pyproj>=2.0
- pip
- pip:
  - git+git://github.com/modflowpy/flopy@develop
  - git+git://github.com/aleaf/gis-utils@develop

