name: mfexport
channels:
- conda-forge
- defaults
dependencies:
- python=3.*
- pyyaml
- numpy
- pandas
- gdal
- fiona
- rasterio>=1.0
- shapely
- pyproj>=2.0
- pip
- pip:
  - https://github.com/modflowpy/flopy/zipball/develop

