name: mfexport_ci
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- numpy
- pandas
- gdal
- fiona
- rasterio
- shapely
- pyproj>=2.0
- codecov
- coverage
- flake8
- pytest
- sphinx
- numpydoc
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
    - git+git://github.com/modflowpy/flopy@develop
    - git+git://github.com/aleaf/gis-utils@develop
